//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kasahorow.KeyboardInstaller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kasahorow.KeyboardInstaller.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;countries&gt;
        ///      &lt;country Name=&quot;Nigera&quot;&gt;
        ///        &lt;keyboards&gt;
        ///          &lt;keyboard Name=&quot;Yoruba&quot; Setup=&quot;keyboards/nigeria/yoruba/setup.exe&quot; DisplayName=&quot;Nigeria - Yoruba Keyboard Layout&quot; Version=&quot;1.0.3.40&quot; Publisher=&quot;Kasahorow&quot;&gt;&lt;/keyboard&gt;
        ///          &lt;keyboard Name=&quot;Igbo&quot; Setup=&quot;keyboards/nigeria/igbo/setup.exe&quot; DisplayName=&quot;Nigeria - Igbo Keyboard Layout&quot; Version=&quot;1.0.3.40&quot; Publisher=&quot;Kasahorow&quot;&gt;&lt;/keyboard&gt;
        ///          &lt;keyboard Name=&quot;Hausa&quot; Setu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string configuration {
            get {
                return ResourceManager.GetString("configuration", resourceCulture);
            }
        }
    }
}
